# Site settings
title: "HOPE"
description: "HOPE Ministries International is a non-profit organization focused on poverty relief in Kenya."

url: "http://hmiafrica.org"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed